name: Output Information
on: workflow_dispatch
jobs:
    output_info:
        runs-on: ubuntu-latest
        steps:
            - name: Get github output context 
              run: echo "The github context is ${{ toJson(github) }}"